### ISSUE TITLE
Incompatible with `bytes` version `1.2` and above

### ISSUE THREAD

**Issue by theRookieCoder** [XAMPPRocky/octocrab#235] opened 2022-08-14 13:55 UTC
Because of the dependency on `hyperx` (whose repository is stale/inactive), the `size` dependency cannot be upgraded on any project that uses `octocrab`.

**Comment by XAMPPRocky** [comment] 2022-08-14 14:36
Thank you for your issue! As noted in #110 I'm not interested in replacing `hyperx` without a viable alternative, so this issue is blocked on `headers` or an equivalent crate providing that alternative. See https://github.com/hyperium/headers/pull/113 for the latest attempt to get this merged into `headers`. For now I'm going to close this as a duplicate of #110

**Closed by XAMPPRocky** 2022-08-14 14:36 UTC

**Comment by theRookieCoder** [comment] 2022-08-14 14:56
Great, tahank you so much for creating and maintaining this project!

**Comment by theRookieCoder** [comment] 2022-10-01 16:59
Just a little update, because of hyperx `url` is also bound to `2.2`

**Comment by theRookieCoder** [comment] 2023-03-23 17:15
Thanks for fixing this issue! The 2 dependency woes I had with `url` and `bytes` have been fixed now!
